name: ewallet
description: A new Flutter project./
publish_to: 'none'
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.2.0
  mobx: ^2.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_modular_test: ^1.0.1
  mobx_codegen: ^2.0.1+3
  mockito: ^5.0.7

flutter:
  uses-material-design: true
  assets:
    - lib/app/shared/assets/img/logo.png
    - lib/app/shared/assets/img/arrow_right.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
